### ISSUE TITLE
When I generate APK and start smartconfig, app closes.

### ISSUE THREAD

**Issue by jomiva** [nguyenvanquan7826/React-Native-Smart-Config-Quan#2]
Does it need any permission or any extra config like in manifest?

**Comment by jomiva** [comment]
`  const startSmartConfig = () => {
    setIsLoading(true);
    const timeOut = 30 * 1000;
    SmartConfig.start("Palixmajo", '90:f6:52:9f:39:1e', "123456", timeOut, (event) => {
      SmartConfig.stop();
      setIsLoading(false);
    });
  };`

**Comment by jomiva** [comment]
`  const startSmartConfig = () => {
    setIsLoading(true);
    const timeOut = 30 * 1000;
    SmartConfig.start("Palixmajo", '90:f6:52:9f:39:1e', "123456", timeOut, (event) => {
      SmartConfig.stop();
      setIsLoading(false);
    });
  };`

**Comment by jomiva** [comment]
It works while I'm developing but when I run assembleRelease and start to do the smartConfig.start, the app closes. Not sure if I need to request any permissions or something?

**Comment by nguyenvanquan7826** [comment]
No, It not need permission. Can you try my code only and not add any code, then build release.
If it still stop app, please add `debuggable true` into build.gradle to see log error in Logcat Android studio.

```
buildTypes {
    release {
        ...
        debuggable true
    }
}
```

**Comment by jomiva** [comment]
> Hi, I found this issue. Please add in manifest
> 
> ```
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
> <uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
> ```

I could make it work adding these permissions to manifest
![image](https://user-images.githubusercontent.com/48603039/99905259-30367280-2ca6-11eb-9694-a554a608cded.png)

then in RN file, asking for those permissions
![image](https://user-images.githubusercontent.com/48603039/99905289-565c1280-2ca6-11eb-9141-998087cb8796.png)

here is my startSmartConfig function
![image](https://user-images.githubusercontent.com/48603039/99905310-768bd180-2ca6-11eb-8088-0d141d203c80.png)

and my btn component
![image](https://user-images.githubusercontent.com/48603039/99905332-8a373800-2ca6-11eb-95bf-0c783047bf69.png)

Seems working at my S9 Android 10. Any updates I'll post it here 👍 
Hope this could help to anyone else.

**Comment by nguyenvanquan7826** [comment]
@jomiva thank you.
